//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobileApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vonalkód beolvasása.
        /// </summary>
        internal static string BarcodePageTitle {
            get {
                return ResourceManager.GetString("BarcodePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keresés a termékek között.
        /// </summary>
        internal static string BarcodePopupViewTitle {
            get {
                return ResourceManager.GetString("BarcodePopupViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vonalkód.
        /// </summary>
        internal static string BarcodeTitle {
            get {
                return ResourceManager.GetString("BarcodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Törlés.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leírás.
        /// </summary>
        internal static string DescriptionPlaceholder {
            get {
                return ResourceManager.GetString("DescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termék sikeresen hozzáadva az aktív bevásárlókosárhoz..
        /// </summary>
        internal static string ItemAddedAlert {
            get {
                return ResourceManager.GetString("ItemAddedAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termék sikeresen eltávolítva az aktív bevásárlókosárból..
        /// </summary>
        internal static string ItemRemovedAlert {
            get {
                return ResourceManager.GetString("ItemRemovedAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termékek.
        /// </summary>
        internal static string ItemsTitle {
            get {
                return ResourceManager.GetString("ItemsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem található termék a vonalkódhoz, az alábbi gomb segítségével hozzárendelheti egy létező termékhez..
        /// </summary>
        internal static string NoItemsFoundForBarcode {
            get {
                return ResourceManager.GetString("NoItemsFoundForBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ár.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termék keresése.
        /// </summary>
        internal static string SearchItems {
            get {
                return ResourceManager.GetString("SearchItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keresés....
        /// </summary>
        internal static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolt.
        /// </summary>
        internal static string Shop {
            get {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bevásárlókosár sikeresen létrehozva..
        /// </summary>
        internal static string ShoppingCartAddedAlert {
            get {
                return ResourceManager.GetString("ShoppingCartAddedAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bevásárlókosár neve.
        /// </summary>
        internal static string ShoppingCartNamePlaceholder {
            get {
                return ResourceManager.GetString("ShoppingCartNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bevásárlókosár.
        /// </summary>
        internal static string ShoppingCartTitle {
            get {
                return ResourceManager.GetString("ShoppingCartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helyettesítés.
        /// </summary>
        internal static string Substitute {
            get {
                return ResourceManager.GetString("Substitute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kosárba.
        /// </summary>
        internal static string ToShoppingCart {
            get {
                return ResourceManager.GetString("ToShoppingCart", resourceCulture);
            }
        }
    }
}
